# Generated by Django 6.0.6 on 2026-06-17 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MissingPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('age', models.IntegerField()),
                ('missing_date', models.DateField()),
                ('last_seen_Location', models.CharField(max_length=300)),
                ('contact_info', models.CharField(max_length=200)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='missing_photos/')),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
